name: Deploy

on:
  push:
    branches:
      - main  # or master, whatever your branch is

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/oebb.macistry.com
            git pull
            npm install
            pm2 restart oebb.macistry.com